<a href="https://colab.research.google.com/github/BineetaMishra/DeepLearning/blob/main/Restaurant_review_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NATURAL LANGUAGE PROCESSING***

This task will do the sentiment analysis of the Restaurant reviews. Bag of words Creation. will also happen here. The reviews will be predicted whether it is a negative r positive review.
The datatset here is a tsv file. A csv file is a comma seperated file and a tsv file is tab sepersted Delimiter= \t (tab)

# Importing the Librarires

In [4]:
#importing the libraries
import numpy as np
import pandas as pd

# Importing the Dataset

In [5]:
#Importing the dataset. Here it is a tsv file
#delimiter='\t' used for tsv files
#quoting =3, to ignoring the ""(double quotes) from the dateset.It is done to remove the sparsing error.
#As it can lead to execution error.
dataset= pd.read_csv('/content/drive/MyDrive/Dataset/Restaurant_Reviews.tsv', delimiter='\t', quoting=3)

# Cleaning the Dataset.
Deep cleaning of text. So far the text has punctuation, diff characters other than letters, Capital letters, lower case letters, numbers. Thus we need to simplify the text and this is called deep cleaning in order to ease the  learning process of the training process.
The libraries used are:-
1. **re** -->library. used to simplify the reviews
2. **nltk** ->Classic library in NLP, which will allow us to download the emsemble of stop words.
3. **StopWords**-->These are words we do not want to inclue in the reviews after cleaning the text as they are not prevelant to help classify the reviews as positive or negative. These words include-> Articles, Pronouns.
4. **PorterStemmer** is a class which helps in apply stemming on reviews. Stemming consisites of taking only the root of the word which is enough to understand the word. example for "loved" it will take "Love".

In [3]:
#Cleaning the datatset
import re
import nltk
nltk.download('stopwords') #--> downloads the stopwords
from nltk.corpus import stopwords #--> imports the stopwords in our code.
from nltk.stem.porter import PorterStemmer
corpus=[] #--> empty list to save teh new list
# making a for loop to iterate through all the reviews of the dataset and cleaning the reviews..
for i in range(0, 1000):
  review= re.sub('[^a~zA~Z]', ' ',dataset['Review'][i] )#creting a cleaned review. Removing the punctuation from teh etxts.
  review= review.lower() #transform all the Capital letters to Lower case
  review= review.split() #prepare for stemming. Spilt diff elements in diff words. Then stemming can be applued to each word.
  ps = PorterStemmer() #stemming. Simplifying each word by Root of teh word.
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review= [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review= ' '.join(review)#joining the reviews again
  corpus.append(review)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


# Creating the Bag of Words Model
Create  a sparse matrix. All the words taken from all the reviews.
Each cell will get 0 or 1. 0 if the word in the column is not in the review of the row. 1 if the word in the column is in the review of the row.
The process of creating all the columns taken from each of the word taken from all the reviews is called ***Tokenization***. 

In [7]:
# Proceeding with Tokenization to create the 
#Sparse matrix containing all the reviews in diff rows and all teh words from all the reviews in diff col.
#1 if word is in review and 0 otherwise. We will do tokenization from sklearn  module called feature extraction 
#class--> CounterVectorizer
#take most freq words in teh sparse matrix
#fit the corpus to X, Take all the words from all the reviews in the corpus 
#and then use transform part to put all the words in the columns
#toarray()---> matrix of features must be a 2D array. 
from sklearn.feature_extraction.text import CountVectorizer
#cv= CountVectorizer(max_features=1500) use this only after we know how mnay words are there.
cv= CountVectorizer()
X= cv.fit_transform(corpus).toarray()
Y= dataset.iloc[:, -1].values

In [14]:
X

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
len(X[0]) # use 1500

5

# Splitting the dataset

In [10]:
#Splitting the dataset into the training and test set.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25)

# Training the Dataset on the Naive Bayes model.

In [11]:
## Training the Naive Bayes Model on the Training Set.
from sklearn.naive_bayes import GaussianNB
classifire = GaussianNB()
classifire.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

# Predicting the Test set Result

In [12]:
#### Prediction the test set result

y_pred = classifire.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]

# Making the confusion Matrix

In [13]:
## Making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[124   2]
 [111  13]]


0.548