<a href="https://colab.research.google.com/github/BineetaMishra/DeepLearning/blob/main/Udemy_ANN_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***ARTIFICIAL NEURAL NETWORK***
***CLASSIFICATION CASE.***


***Importing the Libraries***

In [34]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [35]:
#To check if it is using a tensorflow version greater than or equal  2.0
tf.__version__ 

'2.4.0'

# ***Part1:***
***DATA PREPROCESSING***

In [36]:
# Importing the dataset. assigning x as in-dependent variable and y as dependent variable
dataset = pd.read_csv('/content/drive/MyDrive/Dataset/Churn_Modelling.csv')
x= dataset.iloc[:, 3:-1].values
y= dataset.iloc[:, -1].values

In [37]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


***Encoding the Categorical Data.***

There are 2 categorical variables:
1. Geography
2. Gender

In [38]:
# LABEL ENCODING THE GENDER COLUMN
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder() # le is instance of the LabelEncoder class
x[:, 2]= le.fit_transform(x[:, 2])

In [39]:
#One Hot Encoding for the Geography column
# One Hot encoding is performed because there is no connection betwwen
#France, Spain and Germany
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') 
X= np.array(ct.fit_transform(x))

In [40]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into Training and Test set.

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [42]:
# FEATURE SCALING. THIS IS COMPULSARY FOR DL
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [60]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# ***PART 2: BUILDING THE ANN***

In [43]:
# INITIALIZING THE ANN
#CREATING A ANN VARIABLE
ann = tf.keras.models.Sequential() #Sequential class is taken from keras library

In [44]:
#ADDING THE INPUT LAYER AND THE FIRST HIDDEN LAYER
#the fully connected layer that we are creating is an object of the Dense Class
#ann.add(tf.keras.layers.Dense(units(#no.of hidden neurons we want in input layer.)))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [45]:
#ADDING THE SECOND HIDDEN LAYER
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [46]:
#ADDING THE OUTPUT LAYER. AF=sigmoid because it will get the probability of binary outcome.
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# ***PART 3: TRAINING THE ANN***

Compile the ANN with an optimizer, loss function and metrics.

In [47]:
#Compiling the ANN, it has 3 paramets: optimizer, loss, metrics
#binary classification the loss function should be binary_crossentropy, and non binary is categorical_crossentropy
#metrics goes in a [] because we can use many diff types of metrics and it should be entered as a list.
ann.compile(optimizer='adam', loss='binary_crossentropy' , metrics=['accuracy'])

In [48]:
#TRAINING TEH ANN ON THE Training Set.
#Method to change any training model is the fit method
# batch training is always more efficient in ANN. 32 is default value
ann.fit(x_train, y_train, batch_size= 32, epochs=10)

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.5773 - accuracy: 0.7373
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4632 - accuracy: 0.8009
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4586 - accuracy: 0.7925
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4469 - accuracy: 0.7902
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4185 - accuracy: 0.8051
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4208 - accuracy: 0.8104
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4291 - accuracy: 0.8057
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.8054
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4125 - accuracy: 0.8141
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 0.8013

# ***PART 4: MAKING THE PREDICTIONS.***

In [65]:
# Predicting the test result
y_pred= ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [66]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [67]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 287  118]]


0.8215

# PREDICTING THE RESULT ON SINGLE OBSERVATION

Use our ANN model to predict if the cutomer with following information will leave the bank:



solution:
Important Note 1: notice that teh values of teh features were all input in a double pair of square brackets. That's because the predict method always expects a 2D array as the format of it's input. And putting our values in a double pair of square bracketsmakes the input exactly a 2D array.
Be careful of the Dummy variable
Remember to apply scaling.
Important Note 2: Notice also that the 'France' country was not input as a string in the last column but as "1,0,0" in the first three columns.
That is because of course the predict method expects the one-not encoded values of the state, and as we see in te forst row of the matrix of features x, 'France' was encoded as "1,0,0". THE DUMMY VARIABLES ARE ALWAYS CREATED IN THE FIRST COLUMNS.

In [ ]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000,]]))